# -*- coding: utf-8 -*-
"""transaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgsgIEPw7XcZ8WrrRUR8GCxaU2tupqiO
"""

import json
import hashlib
import time

'''
first draft of the transaction will come back and refine later working on  the block file now
'''

timestamp = time.time()
from_ = input("enter the account to transfer from: ")
to = input("enter the account to transfer to: ")
amount = input("enter the amount to transfer:")
data = {
    timestamp,
    "from": from_,
    "to": to,
    "amount": amount
}
hash = hashlib.sha256()
filename = f"{hash}.json"

with open(filename, "w") as file:
    json.dump(data, file, indent=4)

print(f"Data successfully saved to {filename}")